### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by bshefflette** [fchierad/PRD#19]
I am having to visit the names and paths of these methods  several times during development.  Can we discuss having more consistency w/ naming & which module some functions are a part of?
e.g. `PRD.IDVget() PRD.web.form.getValue()`
These stem from `module.IDVault.get` & `module.form.getValue`, that consistency of those stemming objects was nice, worth discussing?

**Comment by fchierad** [comment]
worth discussing - yes. 

Initial reason for the IDVget and IDVglobalQuery naming was to enforce different naming from the RBPM product's shipping functions. That decision was made to avoid confusion with the product's shipping methods, since the ones in this module have different behavior from the shipping ones. 

Imagine having to remember a different set of behaviors/return types for things that are named exactly the same - I'd expect that to cause more confusion for end users of the module. 

The from and field portion are direct exports of the native module, just exposed on a public scope. That is why their function names and behaviors stayed the same.
