### ISSUE TITLE
Web Support for unique & compare

### ISSUE THREAD

**Issue by bshefflette** [fchierad/PRD#20]
could you provide web support for unique & compare?  (and lowercase the names if possible)

**Comment by fchierad** [comment]
I can, main challenge is that both were designed for the engine to be able to handle both array and vector inputs. Since browsers do not support Java the Vector portion would not be valid there, so would need to either have 2 different sets of behaviors in each environment or change them to support only arrays and either let those using them in the engine perform their own conversions or provide a wrapper for the conversions in the engine side.

**Comment by fchierad** [comment]
renamed, code complete, unit tests updated for the engine side and passed. manual testing performed on the form side to validate behavior using same arrays from engine unit tests.
